reordering template for dynamic update that is soft reconfig
Azure/cyclecloud-symphony pull request #24
Opened 2023-05-17 20:25 UTC by nidhi0622

2023-05-17 21:02 UTC, bwatrous requested changes

2023-05-17 21:02 UTC, bwatrous commented on specs/master/cluster-init/files/host_provider/test/capacity_tracker_test.py
> +        self.assertFalse(db.is_paused("execute", "A4"))
It looks like you're verifying that capacity is NOT paused.
Am I misreading?

2023-05-22 16:32 UTC, bwatrous requested changes

2023-05-22 16:32 UTC, bwatrous commented on specs/master/cluster-init/files/host_provider/src/cluster.py
> +        assert len(filtered) == 1
Before release, we should remove the asserts in this method and replace them with an error log and a reasonable alternative (like making no changes or a RuntimeError with reasonable message if they're an expected error condition)

2023-05-22 22:00 UTC, nidhi0622 commented on specs/master/cluster-init/files/host_provider/src/cluster.py
> +        if not disable_active_count_fix:
yeah makes sense :)

2023-05-26 16:39 UTC, bwatrous approved these changes

2023-05-26 16:41 UTC, merged